// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/tetsuzawa/recipesapi/containers/backend/cmd/server/controller"
	"github.com/tetsuzawa/recipesapi/containers/backend/internal/core"
)

// Injectors from wire.go:

func InitializeControllers(db *gorm.DB) *controller.Controllers {
	repository := core.NewGateway(db)
	provider := core.NewProvider(repository)
	controllerController := controller.NewController(provider)
	controllers := controller.NewControllers(controllerController)
	return controllers
}
