version: '3'

services:
  backend:
    image: ${ECR_REPOSITORY_URL}
    build:
      context: ./containers/backend
      dockerfile: ./build/Dockerfile
    tty: true
    restart: always
    ports:
      - 80:80
    volumes:
      - ./containers/backend:/go/src/api
