version: '3'

services:
  backend:
    image: 094908652183.dkr.ecr.ap-northeast-1.amazonaws.com/voyageapi-api
    build:
      context: ./containers/backend
      dockerfile: ./build/Dockerfile
    tty: true
    restart: always
    env_file:
      - ./containers/backend/prod.env
    ports:
      - 80:80
    volumes:
      - ./containers/backend:/go/src/api
    logging:
      driver: awslogs
      options:
        awslogs-group: voyageapi-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: backend
