settings:
  recovery:
    index: true       # print files indexing
    events: false     # print each event
    tools: false      # print each tool
  legacy:
    force: false      # enable polling watcher
    interval: 0s      # polling interval
server:
  status: false       # web panel
  open: true          # open in default browser
  port: 5555          # server port
  host: localhost     # server host
schema:
  - name: server      # project name
    path: .             # project path, '.' is for wdir path
    commands:           # all go commands supported
      install:              # go run
        status: true
        method: go build -o ./bin/server ./cmd/server/
      run:              # go run
        status: true
        method: ./bin/server
    watcher:
      paths:            # paths watched
        - /
      extensions:       # extensions watched
        - go
        - html
        - css
        - js
        - env
      ignored_paths:    # paths ignored
        - .git
        - .realize
        - .idea
        - vendor
        - realize/assets
        - realize/bindata.go
