name: CI Test
on: pull_request

jobs:
  test-merge:
    name: Test
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Change directory into go modules
        run: cd ./containers/backend

      - name: Test
        run: go test ./... -v

